### ISSUE TITLE
node_redis is poorly mantained

### ISSUE THREAD

**Issue by roccomuso** [lukechilds/keyv-redis#25]
https://github.com/NodeRedis/node_redis looks poorly mantained.
Let's consider switching to https://github.com/luin/ioredis

**Comment by lukechilds** [comment]
Is it poorly maintained or just stable so receiving less frequent updates?

Genuinely asking, I'm not too familiar with it. If there are issues with `node_redis` that would be resolved by switching to `ioredis` I'm more than happy to switch.

**Comment by Kikobeats** [comment]
feeling `ioredis` is just [superior](https://github.com/microlinkhq/async-ratelimiter/pull/23#issuecomment-491225856).

Also, switching remove `pify` dependency

**Comment by lukechilds** [comment]
Yeah, I'll happily accept a PR switching to `ioredis`.

**Comment by veeramarni** [comment]
Also `ioredis` supports redis cluster very well.

**Comment by Kikobeats** [comment]
Another reason to use `ioredis` over `node_redis`

`node_redis` doesn't support TLS: 
https://github.com/NodeRedis/node_redis/issues/1331

Basically, because las released was 2 years ago ¯\_(ツ)_/¯
